#pragma once
#include "PPGEpch.h"

namespace PPGE
{
enum class KeyCode : uint16_t
{
    PPGE_KEY_SPACE = 0x0U,
    PPGE_KEY_APOSTROPHE,
    PPGE_KEY_COMMA,
    PPGE_KEY_MINUS,
    PPGE_KEY_PERIOD,
    PPGE_KEY_SLASH,
    PPGE_KEY_0,
    PPGE_KEY_1,
    PPGE_KEY_2,
    PPGE_KEY_3,
    PPGE_KEY_4,
    PPGE_KEY_5,
    PPGE_KEY_6,
    PPGE_KEY_7,
    PPGE_KEY_8,
    PPGE_KEY_9,
    PPGE_KEY_SEMICOLON,
    PPGE_KEY_EQUAL,
    PPGE_KEY_A,
    PPGE_KEY_B,
    PPGE_KEY_C,
    PPGE_KEY_D,
    PPGE_KEY_E,
    PPGE_KEY_F,
    PPGE_KEY_G,
    PPGE_KEY_H,
    PPGE_KEY_I,
    PPGE_KEY_J,
    PPGE_KEY_K,
    PPGE_KEY_L,
    PPGE_KEY_M,
    PPGE_KEY_N,
    PPGE_KEY_O,
    PPGE_KEY_P,
    PPGE_KEY_Q,
    PPGE_KEY_R,
    PPGE_KEY_S,
    PPGE_KEY_T,
    PPGE_KEY_U,
    PPGE_KEY_V,
    PPGE_KEY_W,
    PPGE_KEY_X,
    PPGE_KEY_Y,
    PPGE_KEY_Z,
    PPGE_KEY_LEFT_BRACKET,
    PPGE_KEY_BACKSLASH,
    PPGE_KEY_RIGHT_BRACKET,
    PPGE_KEY_GRAVE_ACCENT,
    PPGE_KEY_WORLD_1,
    PPGE_KEY_WORLD_2,
    PPGE_KEY_ESCAPE,
    PPGE_KEY_ENTER,
    PPGE_KEY_TAB,
    PPGE_KEY_BACKSPACE,
    PPGE_KEY_INSERT,
    PPGE_KEY_DELETE,
    PPGE_KEY_RIGHT,
    PPGE_KEY_LEFT,
    PPGE_KEY_DOWN,
    PPGE_KEY_UP,
    PPGE_KEY_PAGE_UP,
    PPGE_KEY_PAGE_DOWN,
    PPGE_KEY_HOME,
    PPGE_KEY_END,
    PPGE_KEY_CAPS_LOCK,
    PPGE_KEY_SCROLL_LOCK,
    PPGE_KEY_NUM_LOCK,
    PPGE_KEY_PRINT_SCREEN,
    PPGE_KEY_PAUSE,
    PPGE_KEY_F1,
    PPGE_KEY_F2,
    PPGE_KEY_F3,
    PPGE_KEY_F4,
    PPGE_KEY_F5,
    PPGE_KEY_F6,
    PPGE_KEY_F7,
    PPGE_KEY_F8,
    PPGE_KEY_F9,
    PPGE_KEY_F10,
    PPGE_KEY_F11,
    PPGE_KEY_F12,
    PPGE_KEY_F13,
    PPGE_KEY_F14,
    PPGE_KEY_F15,
    PPGE_KEY_F16,
    PPGE_KEY_F17,
    PPGE_KEY_F18,
    PPGE_KEY_F19,
    PPGE_KEY_F20,
    PPGE_KEY_F21,
    PPGE_KEY_F22,
    PPGE_KEY_F23,
    PPGE_KEY_F24,
    PPGE_KEY_F25,
    PPGE_KEY_KP_0,
    PPGE_KEY_KP_1,
    PPGE_KEY_KP_2,
    PPGE_KEY_KP_3,
    PPGE_KEY_KP_4,
    PPGE_KEY_KP_5,
    PPGE_KEY_KP_6,
    PPGE_KEY_KP_7,
    PPGE_KEY_KP_8,
    PPGE_KEY_KP_9,
    PPGE_KEY_KP_DECIMAL,
    PPGE_KEY_KP_DIVIDE,
    PPGE_KEY_KP_MULTIPLY,
    PPGE_KEY_KP_SUBTRACT,
    PPGE_KEY_KP_ADD,
    PPGE_KEY_KP_ENTER,
    PPGE_KEY_KP_EQUAL,
    PPGE_KEY_LEFT_SHIFT,
    PPGE_KEY_LEFT_CONTROL,
    PPGE_KEY_LEFT_ALT,
    PPGE_KEY_LEFT_SUPER,
    PPGE_KEY_RIGHT_SHIFT,
    PPGE_KEY_RIGHT_CONTROL,
    PPGE_KEY_RIGHT_ALT,
    PPGE_KEY_RIGHT_SUPER,
    PPGE_KEY_MENU,
    PPGE_KEY_CODE_COUNT
};

inline std::ostream &operator<<(std::ostream &os, KeyCode keycode)
{
    os << static_cast<uint16_t>(keycode);
    return os;
}

enum class MouseCode : uint16_t
{
    PPGE_MOUSE_BUTTON_0 = 0x0U,
    PPGE_MOUSE_BUTTON_1,
    PPGE_MOUSE_BUTTON_2,
    PPGE_MOUSE_BUTTON_3,
    PPGE_MOUSE_BUTTON_4,
    PPGE_MOUSE_BUTTON_5,
    PPGE_MOUSE_BUTTON_6,
    PPGE_MOUSE_BUTTON_7,
    PPGE_MOUSE_BUTTON_LEFT,
    PPGE_MOUSE_BUTTON_RIGHT,
    PPGE_MOUSE_BUTTON_MIDDLE,
    PPGE_MOUSE_CODE_COUNT
};

inline std::ostream &operator<<(std::ostream &os, MouseCode mousecode)
{
    os << static_cast<uint16_t>(mousecode);
    return os;
}

enum class JoystickCode : uint16_t
{
    PPGE_JOYSTICK_BUTTON_0 = 0x0U,
    PPGE_JOYSTICK_BUTTON_1,
    PPGE_JOYSTICK_BUTTON_2,
    PPGE_JOYSTICK_BUTTON_3,
    PPGE_JOYSTICK_BUTTON_4,
    PPGE_JOYSTICK_BUTTON_5,
    PPGE_JOYSTICK_BUTTON_6,
    PPGE_JOYSTICK_BUTTON_7,
    PPGE_JOYSTICK_BUTTON_8,
    PPGE_JOYSTICK_BUTTON_9,
    PPGE_JOYSTICK_BUTTON_10,
    PPGE_JOYSTICK_BUTTON_11,
    PPGE_JOYSTICK_BUTTON_12,
    PPGE_JOYSTICK_BUTTON_13,
    PPGE_JOYSTICK_BUTTON_14,
    PPGE_JOYSTICK_BUTTON_15,
    PPGE_JOYSTICK_CODE_COUNT
};

inline std::ostream &operator<<(std::ostream &os, JoystickCode joystick_code)
{
    os << static_cast<uint16_t>(joystick_code);
    return os;
}

enum class GamepadCode : uint16_t
{
    PPGE_GAMEPAD_BUTTON_A = 0x0U,
    PPGE_GAMEPAD_BUTTON_B,
    PPGE_GAMEPAD_BUTTON_X,
    PPGE_GAMEPAD_BUTTON_Y,
    PPGE_GAMEPAD_BUTTON_LEFT_BUMPER,
    PPGE_GAMEPAD_BUTTON_RIGHT_BUMPER,
    PPGE_GAMEPAD_BUTTON_BACK,
    PPGE_GAMEPAD_BUTTON_START,
    PPGE_GAMEPAD_BUTTON_GUIDE,
    PPGE_GAMEPAD_BUTTON_LEFT_THUMB,
    PPGE_GAMEPAD_BUTTON_RIGHT_THUMB,
    PPGE_GAMEPAD_BUTTON_DPAD_UP,
    PPGE_GAMEPAD_BUTTON_DPAD_RIGHT,
    PPGE_GAMEPAD_BUTTON_DPAD_DOWN,
    PPGE_GAMEPAD_BUTTON_DPAD_LEFT,
    PPGE_GAMEPAD_BUTTON_CROSS,
    PPGE_GAMEPAD_BUTTON_CIRCLE,
    PPGE_GAMEPAD_BUTTON_SQUARE,
    PPGE_GAMEPAD_BUTTON_TRIANGLE,
    PPGE_GAMEPAD_AXIS_LEFT_X,
    PPGE_GAMEPAD_AXIS_LEFT_Y,
    PPGE_GAMEPAD_AXIS_RIGHT_X,
    PPGE_GAMEPAD_AXIS_RIGHT_Y,
    PPGE_GAMEPAD_AXIS_LEFT_TRIGGER,
    PPGE_GAMEPAD_AXIS_RIGHT_TRIGGER,
    PPGE_GAMEPAD_CODE_COUNT
};

inline std::ostream &operator<<(std::ostream &os, GamepadCode gamepad_button_code)
{
    os << static_cast<uint16_t>(gamepad_button_code);
    return os;
}
} // namespace PPGE

/* Keys */
#define PPGE_KEY_SPACE ::PPGE::KeyCode::PPGE_KEY_SPACE
#define PPGE_KEY_APOSTROPHE ::PPGE::KeyCode::PPGE_KEY_APOSTROPHE /* ' */
#define PPGE_KEY_COMMA ::PPGE::KeyCode::PPGE_KEY_COMMA           /* , */
#define PPGE_KEY_MINUS ::PPGE::KeyCode::PPGE_KEY_MINUS           /* - */
#define PPGE_KEY_PERIOD ::PPGE::KeyCode::PPGE_KEY_PERIOD         /* . */
#define PPGE_KEY_SLASH ::PPGE::KeyCode::PPGE_KEY_SLASH           /* / */
#define PPGE_KEY_0 ::PPGE::KeyCode::PPGE_KEY_0
#define PPGE_KEY_1 ::PPGE::KeyCode::PPGE_KEY_1
#define PPGE_KEY_2 ::PPGE::KeyCode::PPGE_KEY_2
#define PPGE_KEY_3 ::PPGE::KeyCode::PPGE_KEY_3
#define PPGE_KEY_4 ::PPGE::KeyCode::PPGE_KEY_4
#define PPGE_KEY_5 ::PPGE::KeyCode::PPGE_KEY_5
#define PPGE_KEY_6 ::PPGE::KeyCode::PPGE_KEY_6
#define PPGE_KEY_7 ::PPGE::KeyCode::PPGE_KEY_7
#define PPGE_KEY_8 ::PPGE::KeyCode::PPGE_KEY_8
#define PPGE_KEY_9 ::PPGE::KeyCode::PPGE_KEY_9
#define PPGE_KEY_SEMICOLON ::PPGE::KeyCode::PPGE_KEY_SEMICOLON /* ; */
#define PPGE_KEY_EQUAL ::PPGE::KeyCode::PPGE_KEY_EQUAL         /* = */
#define PPGE_KEY_A ::PPGE::KeyCode::PPGE_KEY_A
#define PPGE_KEY_B ::PPGE::KeyCode::PPGE_KEY_B
#define PPGE_KEY_C ::PPGE::KeyCode::PPGE_KEY_C
#define PPGE_KEY_D ::PPGE::KeyCode::PPGE_KEY_D
#define PPGE_KEY_E ::PPGE::KeyCode::PPGE_KEY_E
#define PPGE_KEY_F ::PPGE::KeyCode::PPGE_KEY_F
#define PPGE_KEY_G ::PPGE::KeyCode::PPGE_KEY_G
#define PPGE_KEY_H ::PPGE::KeyCode::PPGE_KEY_H
#define PPGE_KEY_I ::PPGE::KeyCode::PPGE_KEY_I
#define PPGE_KEY_J ::PPGE::KeyCode::PPGE_KEY_J
#define PPGE_KEY_K ::PPGE::KeyCode::PPGE_KEY_K
#define PPGE_KEY_L ::PPGE::KeyCode::PPGE_KEY_L
#define PPGE_KEY_M ::PPGE::KeyCode::PPGE_KEY_M
#define PPGE_KEY_N ::PPGE::KeyCode::PPGE_KEY_N
#define PPGE_KEY_O ::PPGE::KeyCode::PPGE_KEY_O
#define PPGE_KEY_P ::PPGE::KeyCode::PPGE_KEY_P
#define PPGE_KEY_Q ::PPGE::KeyCode::PPGE_KEY_Q
#define PPGE_KEY_R ::PPGE::KeyCode::PPGE_KEY_R
#define PPGE_KEY_S ::PPGE::KeyCode::PPGE_KEY_S
#define PPGE_KEY_T ::PPGE::KeyCode::PPGE_KEY_T
#define PPGE_KEY_U ::PPGE::KeyCode::PPGE_KEY_U
#define PPGE_KEY_V ::PPGE::KeyCode::PPGE_KEY_V
#define PPGE_KEY_W ::PPGE::KeyCode::PPGE_KEY_W
#define PPGE_KEY_X ::PPGE::KeyCode::PPGE_KEY_X
#define PPGE_KEY_Y ::PPGE::KeyCode::PPGE_KEY_Y
#define PPGE_KEY_Z ::PPGE::KeyCode::PPGE_KEY_Z
#define PPGE_KEY_LEFT_BRACKET ::PPGE::KeyCode::PPGE_KEY_LEFT_BRACKET   /* [ */
#define PPGE_KEY_BACKSLASH ::PPGE::KeyCode::PPGE_KEY_BACKSLASH         /* \ */
#define PPGE_KEY_RIGHT_BRACKET ::PPGE::KeyCode::PPGE_KEY_RIGHT_BRACKET /* ] */
#define PPGE_KEY_GRAVE_ACCENT ::PPGE::KeyCode::PPGE_KEY_GRAVE_ACCENT   /* ` */
#define PPGE_KEY_WORLD_1 ::PPGE::KeyCode::PPGE_KEY_WORLD_1             /* non-US #1 */
#define PPGE_KEY_WORLD_2 ::PPGE::KeyCode::PPGE_KEY_WORLD_2             /* non-US #2 */

/* Functions */
#define PPGE_KEY_ESCAPE ::PPGE::KeyCode::PPGE_KEY_ESCAPE
#define PPGE_KEY_ENTER ::PPGE::KeyCode::PPGE_KEY_ENTER
#define PPGE_KEY_TAB ::PPGE::KeyCode::PPGE_KEY_TAB
#define PPGE_KEY_BACKSPACE ::PPGE::KeyCode::PPGE_KEY_BACKSPACE
#define PPGE_KEY_INSERT ::PPGE::KeyCode::PPGE_KEY_INSERT
#define PPGE_KEY_DELETE ::PPGE::KeyCode::PPGE_KEY_DELETE
#define PPGE_KEY_RIGHT ::PPGE::KeyCode::PPGE_KEY_RIGHT
#define PPGE_KEY_LEFT ::PPGE::KeyCode::PPGE_KEY_LEFT
#define PPGE_KEY_DOWN ::PPGE::KeyCode::PPGE_KEY_DOWN
#define PPGE_KEY_UP ::PPGE::KeyCode::PPGE_KEY_UP
#define PPGE_KEY_PAGE_UP ::PPGE::KeyCode::PPGE_KEY_PAGE_UP
#define PPGE_KEY_PAGE_DOWN ::PPGE::KeyCode::PPGE_KEY_PAGE_DOWN
#define PPGE_KEY_HOME ::PPGE::KeyCode::PPGE_KEY_HOME
#define PPGE_KEY_END ::PPGE::KeyCode::PPGE_KEY_END
#define PPGE_KEY_CAPS_LOCK ::PPGE::KeyCode::PPGE_KEY_CAPS_LOCK
#define PPGE_KEY_SCROLL_LOCK ::PPGE::KeyCode::PPGE_KEY_SCROLL_LOCK
#define PPGE_KEY_NUM_LOCK ::PPGE::KeyCode::PPGE_KEY_NUM_LOCK
#define PPGE_KEY_PRINT_SCREEN ::PPGE::KeyCode::PPGE_KEY_PRINT_SCREEN
#define PPGE_KEY_PAUSE ::PPGE::KeyCode::PPGE_KEY_PAUSE
#define PPGE_KEY_F1 ::PPGE::KeyCode::PPGE_KEY_F1
#define PPGE_KEY_F2 ::PPGE::KeyCode::PPGE_KEY_F2
#define PPGE_KEY_F3 ::PPGE::KeyCode::PPGE_KEY_F3
#define PPGE_KEY_F4 ::PPGE::KeyCode::PPGE_KEY_F4
#define PPGE_KEY_F5 ::PPGE::KeyCode::PPGE_KEY_F5
#define PPGE_KEY_F6 ::PPGE::KeyCode::PPGE_KEY_F6
#define PPGE_KEY_F7 ::PPGE::KeyCode::PPGE_KEY_F7
#define PPGE_KEY_F8 ::PPGE::KeyCode::PPGE_KEY_F8
#define PPGE_KEY_F9 ::PPGE::KeyCode::PPGE_KEY_F9
#define PPGE_KEY_F10 ::PPGE::KeyCode::PPGE_KEY_F10
#define PPGE_KEY_F11 ::PPGE::KeyCode::PPGE_KEY_F11
#define PPGE_KEY_F12 ::PPGE::KeyCode::PPGE_KEY_F12
#define PPGE_KEY_F13 ::PPGE::KeyCode::PPGE_KEY_F13
#define PPGE_KEY_F14 ::PPGE::KeyCode::PPGE_KEY_F14
#define PPGE_KEY_F15 ::PPGE::KeyCode::PPGE_KEY_F15
#define PPGE_KEY_F16 ::PPGE::KeyCode::PPGE_KEY_F16
#define PPGE_KEY_F17 ::PPGE::KeyCode::PPGE_KEY_F17
#define PPGE_KEY_F18 ::PPGE::KeyCode::PPGE_KEY_F18
#define PPGE_KEY_F19 ::PPGE::KeyCode::PPGE_KEY_F19
#define PPGE_KEY_F20 ::PPGE::KeyCode::PPGE_KEY_F20
#define PPGE_KEY_F21 ::PPGE::KeyCode::PPGE_KEY_F21
#define PPGE_KEY_F22 ::PPGE::KeyCode::PPGE_KEY_F22
#define PPGE_KEY_F23 ::PPGE::KeyCode::PPGE_KEY_F23
#define PPGE_KEY_F24 ::PPGE::KeyCode::PPGE_KEY_F24
#define PPGE_KEY_F25 ::PPGE::KeyCode::PPGE_KEY_F25

/* Keypad */
#define PPGE_KEY_KP_0 ::PPGE::KeyCode::PPGE_KEY_KP_0
#define PPGE_KEY_KP_1 ::PPGE::KeyCode::PPGE_KEY_KP_1
#define PPGE_KEY_KP_2 ::PPGE::KeyCode::PPGE_KEY_KP_2
#define PPGE_KEY_KP_3 ::PPGE::KeyCode::PPGE_KEY_KP_3
#define PPGE_KEY_KP_4 ::PPGE::KeyCode::PPGE_KEY_KP_4
#define PPGE_KEY_KP_5 ::PPGE::KeyCode::PPGE_KEY_KP_5
#define PPGE_KEY_KP_6 ::PPGE::KeyCode::PPGE_KEY_KP_6
#define PPGE_KEY_KP_7 ::PPGE::KeyCode::PPGE_KEY_KP_7
#define PPGE_KEY_KP_8 ::PPGE::KeyCode::PPGE_KEY_KP_8
#define PPGE_KEY_KP_9 ::PPGE::KeyCode::PPGE_KEY_KP_9
#define PPGE_KEY_KP_DECIMAL ::PPGE::KeyCode::PPGE_KEY_KP_DECIMAL
#define PPGE_KEY_KP_DIVIDE ::PPGE::KeyCode::PPGE_KEY_KP_DIVIDE
#define PPGE_KEY_KP_MULTIPLY ::PPGE::KeyCode::PPGE_KEY_KP_MULTIPLY
#define PPGE_KEY_KP_SUBTRACT ::PPGE::KeyCode::PPGE_KEY_KP_SUBTRACT
#define PPGE_KEY_KP_ADD ::PPGE::KeyCode::PPGE_KEY_KP_ADD
#define PPGE_KEY_KP_ENTER ::PPGE::KeyCode::PPGE_KEY_KP_ENTER
#define PPGE_KEY_KP_EQUAL ::PPGE::KeyCode::PPGE_KEY_KP_EQUAL

/* Modifiers */
#define PPGE_KEY_LEFT_SHIFT ::PPGE::KeyCode::PPGE_KEY_LEFT_SHIFT
#define PPGE_KEY_LEFT_CONTROL ::PPGE::KeyCode::PPGE_KEY_LEFT_CONTROL
#define PPGE_KEY_LEFT_ALT ::PPGE::KeyCode::PPGE_KEY_LEFT_ALT
#define PPGE_KEY_LEFT_SUPER ::PPGE::KeyCode::PPGE_KEY_LEFT_SUPER
#define PPGE_KEY_RIGHT_SHIFT ::PPGE::KeyCode::PPGE_KEY_RIGHT_SHIFT
#define PPGE_KEY_RIGHT_CONTROL ::PPGE::KeyCode::PPGE_KEY_RIGHT_CONTROL
#define PPGE_KEY_RIGHT_ALT ::PPGE::KeyCode::PPGE_KEY_RIGHT_ALT
#define PPGE_KEY_RIGHT_SUPER ::PPGE::KeyCode::PPGE_KEY_RIGHT_SUPER
#define PPGE_KEY_MENU ::PPGE::KeyCode::PPGE_KEY_MENU

/* Mouse Buttons */
#define PPGE_MOUSE_BUTTON_0 ::PPGE::MouseCode::PPGE_MOUSE_BUTTON_0
#define PPGE_MOUSE_BUTTON_1 ::PPGE::MouseCode::PPGE_MOUSE_BUTTON_1
#define PPGE_MOUSE_BUTTON_2 ::PPGE::MouseCode::PPGE_MOUSE_BUTTON_2
#define PPGE_MOUSE_BUTTON_3 ::PPGE::MouseCode::PPGE_MOUSE_BUTTON_3
#define PPGE_MOUSE_BUTTON_4 ::PPGE::MouseCode::PPGE_MOUSE_BUTTON_4
#define PPGE_MOUSE_BUTTON_5 ::PPGE::MouseCode::PPGE_MOUSE_BUTTON_5
#define PPGE_MOUSE_BUTTON_6 ::PPGE::MouseCode::PPGE_MOUSE_BUTTON_6
#define PPGE_MOUSE_BUTTON_7 ::PPGE::MouseCode::PPGE_MOUSE_BUTTON_7
#define PPGE_MOUSE_BUTTON_LEFT ::PPGE::MouseCode::PPGE_MOUSE_BUTTON_LEFT
#define PPGE_MOUSE_BUTTON_RIGHT ::PPGE::MouseCode::PPGE_MOUSE_BUTTON_RIGHT
#define PPGE_MOUSE_BUTTON_MIDDLE ::PPGE::MouseCode::PPGE_MOUSE_BUTTON_MIDDLE

/* Joystick Buttons */
#define PPGE_JOYSTICK_BUTTON_0 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_0
#define PPGE_JOYSTICK_BUTTON_1 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_1
#define PPGE_JOYSTICK_BUTTON_2 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_2
#define PPGE_JOYSTICK_BUTTON_3 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_3
#define PPGE_JOYSTICK_BUTTON_4 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_4
#define PPGE_JOYSTICK_BUTTON_5 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_5
#define PPGE_JOYSTICK_BUTTON_6 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_6
#define PPGE_JOYSTICK_BUTTON_7 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_7
#define PPGE_JOYSTICK_BUTTON_8 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_8
#define PPGE_JOYSTICK_BUTTON_9 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_9
#define PPGE_JOYSTICK_BUTTON_10 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_10
#define PPGE_JOYSTICK_BUTTON_11 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_11
#define PPGE_JOYSTICK_BUTTON_12 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_12
#define PPGE_JOYSTICK_BUTTON_13 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_13
#define PPGE_JOYSTICK_BUTTON_14 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_14
#define PPGE_JOYSTICK_BUTTON_15 ::PPGE::JoystickCode::PPGE_JOYSTICK_BUTTON_15

/* Gamepad Buttons */
#define PPGE_GAMEPAD_BUTTON_A ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_A
#define PPGE_GAMEPAD_BUTTON_B ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_B
#define PPGE_GAMEPAD_BUTTON_X ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_X
#define PPGE_GAMEPAD_BUTTON_Y ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_Y
#define PPGE_GAMEPAD_BUTTON_LEFT_BUMPER ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_LEFT_BUMPER
#define PPGE_GAMEPAD_BUTTON_RIGHT_BUMPER ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_RIGHT_BUMPER
#define PPGE_GAMEPAD_BUTTON_BACK ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_BACK
#define PPGE_GAMEPAD_BUTTON_START ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_START
#define PPGE_GAMEPAD_BUTTON_GUIDE ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_GUIDE
#define PPGE_GAMEPAD_BUTTON_LEFT_THUMB ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_LEFT_THUMB
#define PPGE_GAMEPAD_BUTTON_RIGHT_THUMB ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_RIGHT_THUMB
#define PPGE_GAMEPAD_BUTTON_DPAD_UP ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_DPAD_UP
#define PPGE_GAMEPAD_BUTTON_DPAD_RIGHT ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_DPAD_RIGHT
#define PPGE_GAMEPAD_BUTTON_DPAD_DOWN ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_DPAD_DOWN
#define PPGE_GAMEPAD_BUTTON_DPAD_LEFT ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_DPAD_LEFT
#define PPGE_GAMEPAD_BUTTON_CROSS ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_CROSS
#define PPGE_GAMEPAD_BUTTON_CIRCLE ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_CIRCLE
#define PPGE_GAMEPAD_BUTTON_SQUARE ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_SQUARE
#define PPGE_GAMEPAD_BUTTON_TRIANGLE ::PPGE::GamepadCode::PPGE_GAMEPAD_BUTTON_TRIANGLE

/* Gamepad Thumbsticks */
#define PPGE_GAMEPAD_AXIS_LEFT_X ::PPGE::GamepadCode::PPGE_GAMEPAD_AXIS_LEFT_X
#define PPGE_GAMEPAD_AXIS_LEFT_Y ::PPGE::GamepadCode::PPGE_GAMEPAD_AXIS_LEFT_Y
#define PPGE_GAMEPAD_AXIS_RIGHT_X ::PPGE::GamepadCode::PPGE_GAMEPAD_AXIS_RIGHT_X
#define PPGE_GAMEPAD_AXIS_RIGHT_Y ::PPGE::GamepadCode::PPGE_GAMEPAD_AXIS_RIGHT_Y
#define PPGE_GAMEPAD_AXIS_LEFT_TRIGGER ::PPGE::GamepadCode::PPGE_GAMEPAD_AXIS_LEFT_TRIGGER
#define PPGE_GAMEPAD_AXIS_RIGHT_TRIGGER ::PPGE::GamepadCode::PPGE_GAMEPAD_AXIS_RIGHT_TRIGGER
