name: ubuntu-latest build
on:
  push:
    branches: [ core-systems ]
  pull_request:
    branches: [ core-systems ]

jobs:
  ubuntu-latest-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: core-systems
        submodules: recursive

    # install dependencies
    - name: opengl
      run: |
        sudo apt-get install libglu1-mesa-dev
        sudo apt-get install freeglut3-dev
        sudo apt-get install mesa-common-dev
        
    # build project
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H.
    - name: cmake make
      run: cmake --build build/ --target all
