name: ubuntu-latest build
on:
  push:
    branches: [ core-systems ]
  pull_request:
    branches: [ core-systems ]

jobs:
  ubuntu-latest-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: core-systems
        submodules: recursive

    # build project
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H.
    - name: cmake make
      run: cmake --build build/ --target all
